services:
  sonarqube:
    image: docker.io/bitnami/sonarqube:10
    hostname: sonarqube
    container_name: sonarqube
    platform: linux/x86_64
    depends_on:
      - postgres
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      SONARQUBE_USERNAME: "admin"
      SONARQUBE_PASSWORD: "admin"
      SONARQUBE_DATABASE_NAME: "sonar"
      SONARQUBE_DATABASE_USERNAME: "sonar"
      SONARQUBE_DATABASE_PASSWORD: "sonar"
      SONARQUBE_DATABASE_HOST: "postgres"
    volumes:
      - ./sonarqube_data:/bitnami/sonarqube
    ports:
      - "9000:9000"
  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data