apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: filebeat
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    # filebeat.inputs:
    # - type: filestream
    #   id: kubernetes-container-logs
    #   paths:
    #     - /var/log/containers/*.log
    #   parsers:
    #     - container: ~
    #   prospector:
    #     scanner:
    #       fingerprint.enabled: true
    #       symlinks: true
    #   file_identity.fingerprint: ~
    #   processors:
    #     - add_kubernetes_metadata:
    #         host: ${NODE_NAME}
    #         matchers:
    #         - logs_path:
    #             logs_path: "/var/log/containers/"

    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
            - /var/log/containers/*-${data.kubernetes.container.id}.log
            processors:
              - add_kubernetes_metadata:
                  host: ${NODE_NAME}
          templates:
            - condition:
                equals:
                  kubernetes.annotations.co.elastic.logs/enabled: "true"
              config:
                - type: container
                  paths:
                    - /var/log/containers/*-${data.kubernetes.container.id}.log
                  processors:
                    - add_kubernetes_metadata:
                        host: ${NODE_NAME}

            # parsers:
            # - container: ~
            # prospector:
            #  scanner:
            #    fingerprint.enabled: true
            #    symlinks: true
            # file_identity.fingerprint: ~

    # processors:
    #   - add_host_metadata:

    # output.elasticsearch:
    #   hosts: ${ELASTICSEARCH_HOST}
    #   username: ${ELASTICSEARCH_USERNAME}
    #   password: ${ELASTICSEARCH_PASSWORD}
    #   ssl.certificate_authorities: ${SSL_CERTIFICATE_AUTHORITY}
    #   # ssl.certificate: ${SSL_ELASTICSEARCH_CERTIFICATE}
    #   # ssl.key: ${SSL_ELASTICSEARCH_KEY}
    output.logstash:
      hosts: ${LOGSTASH_HOST}
      ssl.certificate_authorities: ${SSL_CERTIFICATE_AUTHORITY}
      ssl.certificate: ${SSL_BEATS_CERTIFICATE}
      ssl.key: ${SSL_BEATS_KEY}
    # setup.kibana:
    #   host: ${KIBANA_HOST}
    #   ssl.enabled: true
    #   ssl.certificate_authorities: ${SSL_CERTIFICATE_AUTHORITY}
    # ssl.certificate: ${SSL_KIBANA_CERTIFICATE}
    # ssl.key: ${SSL_KIBANA_KEY}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-stack
  namespace: filebeat
  labels:
    k8s-app: filebeat
data:
  elasticsearch_hosts: ''
  logstash_host: ''
  kibana_host: ''
