apiVersion: v1
kind: Secret
metadata:
  name: elastic-ssl
  namespace: filebeat
  labels:
    k8s-app: filebeat
type: Opaque
data:
  ca.crt: ""
  beats.crt: ""
  beats.key: ""
 
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: filebeat
  labels:
    k8s-app: filebeat
type: Opaque
stringData:
  username: elastic
  password: ""