apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: example
  project: default
  sources:
  - repoURL: https://github.com/nqhuy44/config-patterns.git
    path: application/example/overlays/dev
    targetRevision: feature/application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
