apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadbalancercontroller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example
  project: default
  sources:
  - repoURL: https://github.com/nqhuy44/config-patterns.git
    path: application/example/dev
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
