services:
  jenkins:
    image: jenkins/jenkins:lts
    user: 0:0 
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    restart: unless-stopped
  # jenkins-agent:
  #   image: jenkins/inbound-agent
  #   container_name: jenkins-agent
  #   restart: unless-stopped
