global:
  iamge:
    repository: quay.io/argoproj/argocd
    tag: ""
  logging:
    format: json
    level: info

configs:
  cm:
    statusbadge.enabled: true

    # Dex configuration
    # dex.config: |
    #   connectors:
    #     # GitHub example
    #     - type: github
    #       id: github
    #       name: GitHub
    #       config:
    #         clientID: aabbccddeeff00112233
    #         clientSecret: $dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
    #         orgs:
    #         - name: your-github-org

    # oidc.config: |
    #   name: AzureAD
    #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
    #   clientID: CLIENT_ID
    #   clientSecret: $oidc.azuread.clientSecret
    #   rootCA: |
    #     -----BEGIN CERTIFICATE-----
    #     ... encoded certificate data here ...
    #     -----END CERTIFICATE-----
    #   requestedIDTokenClaims:
    #     groups:
    #       essential: true
    #   requestedScopes:
    #     - openid
    #     - profile
    #     - email

  admin.enabled: "true"
  accounts.dev: apiKey, login
  accounts.dev.enabled: "true"

  rbac:
    create: false
    policy.csv: |
      g, admin, role:admin
      g, dev, role:dev
    
    policy.admin.csv: |
      # grant all permissions to the admin role
      p, role:admin, applications, *, *, allow
      p, role:admin, applicationsets, *, *, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, projects, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, *, allow
      p, role:admin, extensions, *, *, allow
      g, admin, role:admin
    
    policy.readonly.csv: |
      # grand read-only permissions to the readonly role, read-only role can only view applications
      p, role:readonly, applications, get, *, allow
      p, role:readonly, applications, list, *, allow
      p, role:readonly, projects, get, *, allow
      p, role:readonly, projects, list, *, allow  

    policy.dev.csv: |
      # grand permission to dev role allow to get and list applications and projects, create and sync applications
      p, role:dev, applications, get, *, allow
      p, role:dev, applications, list, *, allow
      p, role:dev, applications, sync, *, allow
      
      p, role:dev, projects, get, *, allow
      p, role:dev, projects, list, *, allow 

    policy.default: role:readonly 
    scopes: '[cognito:groups, email]' 
    policy.matchMode: 'glob'

notifications:
  #https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/overview/
  notifiers: {}
  #https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/subscriptions/
  subscriptions: []
  #https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/templates/
  templates: {}

