apiVersion: batch/v1
kind: Job
metadata:
  name: pre-job
  namespace: example
  labels:
    app: pre-job
spec:
  template:
    spec:
      containers:
      - name: pre-job
        image: debian:latest
        command:
          - /bin/bash
          - -c
          - |
            echo $APP_NAME
        envfrom:
        - configMapRef:
            name: example-config
      restartPolicy: Never