apiVersion: batch/v1
kind: Job
metadata:
  name: pre-job
  namespace: example
  labels:
    app: pre-job
spec:
  template:
    spec:
      containers:
      - name: pre-job
        image: debian:latest
        command: ["echo", "$APP_VERSION"]
        envfrom:
        - configMapRef:
            name: example-config
      restartPolicy: Never