apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, admin, role:admin
    g, dev, role:dev
  
  policy.admin.csv: |
    # grant all permissions to the admin role
    p, role:admin, applications, *, *, allow
    p, role:admin, applicationsets, *, *, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, *, allow
    p, role:admin, extensions, *, *, allow
    
    g, admin, role:admin
  
  policy.readonly.csv: |
    # grand read-only permissions to the readonly role, read-only role can only view applications
    p, role:readonly, applications, get, *, allow
    p, role:readonly, applications, list, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, projects, list, *, allow

  policy.dev.csv: |
    # grand permission to dev role allow to get and list applications and projects, create and sync applications
    p, role:dev, applications, get, *, allow
    p, role:dev, applications, list, *, allow
    p, role:dev, applications, sync, *, allow
    
    p, role:dev, projects, get, *, allow
    p, role:dev, projects, list, *, allow

  policy.default: role:readonly

  scopes: '[cognito:groups, email]'

  policy.matchMode: 'glob'