
# Name of the application
name: example

# Default image used for the application 
image:
  registry: docker.io
  repository: debian
  tag: stable-slim

containerPorts:
  - name: primary
    port: 8080
  - name: secondary
    port: 8081

# -- Additional labels for the application
podLables: {}

# -- Custom command line arguments to pass to the Dex server
customCommands:
  - sleep 3600

# Configmap for the application
configmap:
  data:
    ENV_APP: "abc"
    ENV_VERSION: "1.0.0"
    ENV_REGION: "us-west-2"
    ENV_ENVIRONMENT: "dev"

# External configmap for the application
externalConfigmap: []

# Secret for the application
secret:
  type: Opaque
  mounthPath: /etc/secret/1
  data:
    SECRET_NAME: "secret-default"
    SECRET_KEY: "secret-key"

# External secret for the application
externalSecret: []

# Service account for the application
serviceAccount:
  # -- Enable the creation of the service account
  create: false

# Service for the application
service:
  # -- Type of the service
  type: ClusterIP
  # -- Port for the service
  port: 80
  # -- Target port for the service
  targetPort: 8080
  ## -- Node port for the service (only for NodePort type)
  # nodePort: 30000

# Ingress for the application
ingress:
  # -- Enable the creation of the ingress
  create: false

# Job to run before the deployment
prerequisites:
  enable: true
  name: "pre-install"
  image:
    registry: docker.io
    repository: debian
    tag: stable-slim
  imagePullPolicy: IfNotPresent
  commands:
    - echo "Running the pre-install job"
