controller:
  name: controller
  kind: DaemonSet
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/fpt-load-balancer-internal: "true"
  # podAnnotations:
  #   co.elastic.logs/enabled: "true"
  #   co.elastic.logs/module: "nginx"
  #   co.elastic.logs/fileset.stdout: "access"
  #   co.elastic.logs/fileset.stderr: "error"
  metrics:
    enabled: false
