{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ template "namespace" $ }}
  name: {{ template "cmName" $}}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

{{- if .Values.externalConfigmap }}
{{- range $cm := .Values.externalConfigmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ template "namespace" $ }}
  name: {{ $cm.name }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
data:
  {{- range $key, $value := $cm.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}