{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ingressName" $ }}
  namespace: {{ template "namespace" $ }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    managed-by: {{ .Release.Service }}
{{- end }}