{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secretName" $}}
  namespace: {{ template "namespace" $ }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: {{ .Values.secret.type }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc| quote }}
  {{- end }}
{{- end }}


{{- if .Values.externalSecret }}
{{- range $sec := .Values.externalSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sec.name }}
  namespace: {{ template "namespace" $ }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: {{ $sec.type }}
data:
  {{- if $sec.data }}
  {{- range $key, $value := $sec.data }}
  {{- if $sec.type | eq "Opaque" }}
  {{ $key }}: {{ $value | b64enc| quote }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
